### ISSUE TITLE
Map 3D incomplete..

### ISSUE THREAD

**Issue by FaberVi** [eegeo/eegeo-example-app#48]
Canosa di Puglia is really incomplete.

**Comment by johnbell84** [comment]
Hi D3m0n92,

Thanks for trying our maps!  Sorry for the delay in replying, we've had a lot of correspondence to catch up with since our recent Unity release.  

I'm sorry to hear that Canosa di Puglia wasn't as complete as you'd hoped.  Unfortunately, our procedural maps can only be as complete as the source mapping data that we build them from.  In this case, we were building the town from a snapshot of OpenStreetMap's data taken in March 2016.  

It looks like OpenStreetMap's data has since been updated and now contains a more complete representation of the town.  As such, we should pick it up whenever we next do a databuild for the region.  We have a lot of competing requests for databuilds, which can be expedited subject to commercial agreements.  Please let us know if this applies in your case.  Otherwise, we'll certainly take your interest in Canosa di Puglia into account whenever we choose which areas to build next.

I hope this helps, please let us know if you have any further questions.

Best Regards,

John
