### ISSUE TITLE
map is not loaded

### ISSUE THREAD

**Issue by UrvishPatel92** [eegeo/eegeo-example-app#52]
I was copy paste "https://docs.wrld3d.com/wrld.js/latest/docs/examples/" form this link in my html page
after run html page. This page was loaded but map is not loaded it was showing blank. in console not see any error also.

**Comment by johnbell84** [comment]
Hi Urvish,

Thanks for trying our maps!  Sorry to hear you've had trouble getting up and running.

It's hard to be sure without error messages, but there are two possible problems I'd like to rule out.  Firstly, if you're trying to access your HTML file locally, via your web browser's 'file://' protocol, you may run into problems due to browser security features.  The workaround is to host your HTML page on a local server, as discussed here:

    https://github.com/wrld3d/eegeo.js/issues/18

Secondly, it's worth making sure that the "your_api_key_here" part of the example has been replaced by a valid API key.   These are 32-character hex strings which you can create and manage from the link below (you may need to login to your WRLD account):
 
    https://www.wrld3d.com/apikeys/

If neither of these turn out to be the problem, it would be great if you could keep your browser's console window open, refresh the page and report back any errors you encounter to us.  If you could let us know your browser and operating system as well, that may also help us to investigate.

I hope this helps.

Best Regards,

John

**Comment by jonty-dawson** [comment]
Assuming this fixed issue - closing as part of issue sweep.
