### ISSUE TITLE
Paris map

### ISSUE THREAD

**Issue by wesleynitsckie** [eegeo/eegeo-example-app#55]
Hi,

When will the Paris map data be available for web? I managed to get the Android Paris maps showing but I really need the web version.

**Comment by johnbell84** [comment]
Hi wesleynitsckie,

Thanks for trying our maps!  Unfortunately, Paris isn’t yet available in WRLD.js.  Making new areas available for the web requires us to make a change to our data format.  This is a process we’ve run for large parts of our coverage, but not yet for Paris.

Our goal is to have full coverage of Earth across all platforms.  We tend to prioritize new areas based on business leads, and can expedite work based on commercial agreements.  Please get in touch if that applies, but otherwise we’ll certainly take your interest in a WRLD.js version of Paris into account when we choose which areas of work to concentrate on next.

In the meantime, as you mentioned, you should be able to view Paris with our mobile or desktop builds.

Best Regards,
John
