### ISSUE TITLE
Camera as child of gameobject

### ISSUE THREAD

**Issue by domarchand** [eegeo/eegeo-example-app#58]
Hello,

In the location based application I'm building, the camera needs to follow a GameObject as well as be affected by touch control to rotate around the character to help the user get situated. 

My original plan was to make the camera a child of the GameObject and move the GameObject in the scene using your GeographicToViewportPoint function coupled with GPS location. 

However I'm getting these two errors : 
"Expected a camera with zero translation (position should be represented in cameraOriginECEF)."
"Assertion failed"

I'm guessing the way you detect which parts of the map to display only works when the camera is at the root of the scene. 

Otherwise, how would you suggest I implement a camera that follows the user ? 

Thanks for your feedback, 
David

**Comment by johnbell84** [comment]
Hi domarchand,

This sounds similar to another issue we've had reported:
    
    https://github.com/wrld3d/unity-api/issues/6/

The original reporter's workaround is discussed in the link above.  We hope to address the root cause of the issue soon, but I'm afraid the workaround is probably the best we can suggest in the meantime.  

Please let us know if you have any further questions.

Best Regards,

John

**Comment by domarchand** [comment]
Thanks that makes sense! 

I'm glad to see that there IS a workaround, even though it isn't super optimal.

Thank you for your responsiveness. 
David
