### ISSUE TITLE
Map changes are very inaccurate and removed roads

### ISSUE THREAD

**Issue by domarchand** [eegeo/eegeo-example-app#59]
I know this might not be related to the project itself, but the support form on your website just went into infinite spinning mode, so my message was never sent. 

I don't know what happened, but your map is now very empty and inaccurate.

Here's a screen capture of the map around the Olympic Stadium in Montréal : http://i.imgur.com/mTOIhe5.jpg

The left version was taken a few weeks ago when I was designing mockups for my UI, and the right version is what's being shown currently in my app. 

Is this a mistake or is this a way for you to try to optimize stuff? I really don't think a location based game would work with more than half the streets invisible. (Yes, I am hiding buildings, but even when I bring them back, roads, trees and parks are missing)

Thanks for any update on this,
David

**Comment by johnbell84** [comment]
Hi David,

Thanks for pointing out the issue with the support form.  This has been raised internally and will be looked into as soon as possible.

We've not made any recent changes to our Canada data, so I suspect this problem is probably something to do how the plugin is selecting which Level of Detail (LOD) to display.  A less detailed world will be displayed when the streaming camera is further away, to try to maintain good performance.  We're looking into ways of giving users more control over this, but I was wondering if you found that re-positioning your streaming camera (the one referenced as "Camera" on your WrldMap instance) to be slightly closer to the area you're focusing on helped with the issue at all?

In case it's any help, you can also browse our data with our JavaScript maps.  The link below should display our data at the highest available LOD (similar to your first screenshot), and if you zoom out slightly the LOD will drop and look more similar to your second screenshot.

    https://maps.wrld3d.com/?lat=45.557866&lon=-73.554952&zoom=15&orient=0.002

I hope this helps.  Please let us know if you have any more issues.

Best Regards,

John

**Comment by domarchand** [comment]
This is the issue. The way my setup currently works is that I have one camera above the player model shooting straight down. This camera is used as the camera for Wrld3D.

Meanwhile the second camera attached to the player is used as the active camera for the app. The reason is that when rotating the camera too quickly, it caused some terrible flicker issues while the map was updating. 

This way I always render a circle around the player instead of exactly what's in the current field of view. 

That said, if I lower the camera, I won't be able to render the map very far, or then I'd come back to the flickering issue. 

Would there be a way to render a respectable area around a specific camera without affecting the LOD too much? I know some mobile phones would have some performance issues, which is why having a LOD setting would be amazing though. 

Thanks,

David

**Comment by johnbell84** [comment]
Hi David,

Thanks very much for confirming that, and for the details about what you're building.  This sort of feedback is really useful, and is recorded to help us guide future SDK development.

At present, I think the best I can suggest is to position the streaming camera low over your player (to get the correct LOD) and alter its field of view to cover as wide an area as you think appropriate.  An alternative might be to position your streaming camera in the same place as your render camera, but with a slightly larger field of view, to give things a chance to stream in before being rendered as the camera moves.

Thanks again,

John
